linters:
  enable:
    - govet
    - gofmt
    - misspell
    - unconvert
    - unparam
    - revive
    - unused
    - gocritic
    - deadcode

linters-settings:
  govet:
    enable:
      - shadow
      - loopclosure

  gofmt:
    simplify: true

  misspell:
    locale: US