version: "3"

services:
    db:
        image: postgres:17
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready --dbname ${DB_NAME} --username ${DB_USER}" ]
            interval: 1s
            timeout: 5s

    migrator:
        build: tern
        command:
            - migrate
            - --conn-string
            - postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
            - --migrations
            - /migrations
        depends_on:
            db:
                condition: service_healthy

    server:
        build: .
        environment:
            DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
            PORT: ${PORT}
            JWT_SECRET: ${JWT_SECRET}
            JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
            LOG_LEVEL: ${LOG_LEVEL}
            ADMIN_USERNAME: ${ADMIN_USERNAME}
            ADMIN_EMAIL: ${ADMIN_EMAIL}
            ADMIN_PASSWORD: ${ADMIN_PASSWORD}

        ports:
            - ${EXTERNAL_PORT}:${PORT}
        depends_on:
            -   migrator



volumes:
    db_data: