version: "3"

services:
    db:
        image: postgres:17
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_NAME: ${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

    server:
        build: .
        environment:
            DB_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
            PORT: ${PORT}



volumes:
    db_data:

